Feature : Add cancellable IslandKickEvent
BG-Software-LLC/SuperiorSkyblock2 pull request #1633
Opened 2023-03-07 15:43 UTC by NewZAZ

Add possibility to cancel IslandKickEvent !

2023-03-09 04:59 UTC, OmerBenGera commented
There are commits not related to the feature at all.
Make sure you only push related changes

2023-03-09 06:41 UTC, NewZAZ commented
Oh sorry i didn't see this i fix this

2023-03-09 11:28 UTC, NewZAZ commented
@OmerBenGera it's fixed :)

2023-03-10 18:39 UTC, OmerBenGera requested changes

2023-03-10 18:39 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/superiorskyblock/island/IslandUtils.java
> +        if(plugin.getEventsBus().callIslandKickEvent(caller, target, island))
callIslandKickEvent will return whether the event was successfully called.
Therefore, you want to negate the check - it should return when the method returns false.

2023-03-10 18:39 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/superiorskyblock/mission/MissionsManagerImpl.java
> -
Not relevant to the feature?

2023-03-10 19:01 UTC, NewZAZ commented
That's good @OmerBenGera

2023-03-13 10:38 UTC, SwartZCoding commented
Nice idea to add asap

2023-03-17 14:43 UTC, LuluxClient commented
No 😨

2023-03-18 18:14 UTC, OmerBenGera commented
Why is the MissionsManagerImpl was edited? How is it related to the PR?
Make a proper PR - Create a new branch from dev, make your changes, then submit them.
Only changes related to the PR should be pushed - otherwise, I will reject the PR.

2023-03-18 18:14 UTC, closed without merging