Island Admin Add/Remove & Coop Placeholders.
BG-Software-LLC/SuperiorSkyblock2 pull request #1694
Opened 2023-04-16 19:53 UTC by Oribuin

Implemented request (https://github.com/BG-Software-LLC/SuperiorSkyblock2/discussions/1687), Changed `superior_island_coop_online` to `superior_island_online_coop` to prevent conflicts without additional effort required.

2023-04-16 20:25 UTC, Kristopherrr commented
omer by mistake i forgot to mention that the commands should also have a <target_name> name at the end if u could add it, it would be lovely

2023-04-17 15:18 UTC, OmerBenGera commented
Merge into dev, not master

2023-04-28 11:17 UTC, OmerBenGera requested changes

2023-04-28 11:17 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/superiorskyblock/service/placeholders/PlaceholdersServiceImpl.java
> +                    .put("online_coop", (island, superiorPlayer) -> String.valueOf(island.getCoopPlayers().stream().filter(SuperiorPlayer::isOnline).count()))
This seems to be redundant, as coop players must be online.
As soon as they leave, they'll be uncoop'ed.

2023-04-28 11:17 UTC, OmerBenGera commented on src/main/resources/lang/en-US.yml
> +LEAVE_COOP_ANNOUNCEMENT: '&e&lIsland | &7{0} left the island as a co-op member.'
`UNCOOP_ANNOUNCEMENT` already exists.

2023-04-28 11:28 UTC, OmerBenGera requested changes

2023-04-28 11:28 UTC, OmerBenGera commented on API/src/main/java/com/bgsoftware/superiorskyblock/api/events/IslandCoopRemovePlayerEvent.java
> +public class IslandCoopRemovePlayerEvent extends IslandEvent implements Cancellable {
Rename this to `IslandUncoopPlayerEvent`

2023-04-28 11:28 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/superiorskyblock/commands/admin/CmdAdminAddCoop.java
> +        return List.of("addcoop");
Use `Collections.singletonList` instead.

2023-04-28 11:28 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/superiorskyblock/commands/admin/CmdAdminAddCoop.java
> +public class CmdAdminAddCoop implements IAdminIslandCommand {
Rename to `CmdAdminCoop`

2023-04-28 11:28 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/superiorskyblock/commands/admin/CmdAdminRemoveCoop.java
> +public class CmdAdminRemoveCoop implements IAdminIslandCommand {
Rename to `CmdAdminUncoop`

2023-04-28 11:28 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/superiorskyblock/commands/admin/CmdAdminRemoveCoop.java
> +        return List.of("removecoop");
Change to `Collections.singletonList`

2023-04-28 11:28 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/superiorskyblock/core/events/EventsBus.java
> +    public boolean callIslandRemoveCoopPlayerEvent(Island island, SuperiorPlayer player, SuperiorPlayer target) {
Match to the requested new event name

2023-04-28 11:28 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/superiorskyblock/core/messages/Message.java
> +    COMMAND_DESCRIPTION_ADMIN_ADD_COOP,
Match to the new cmd name

2023-04-28 11:28 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/superiorskyblock/core/messages/Message.java
> +    COMMAND_DESCRIPTION_ADMIN_REMOVE_COOP,
Match to the new cmd name

2023-04-28 11:28 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/superiorskyblock/core/messages/Message.java
> +    LEAVE_COOP_ANNOUNCEMENT,
Should be removed.

2023-04-28 11:28 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/superiorskyblock/service/placeholders/PlaceholdersServiceImpl.java
> +                    .put("island_coop_online", (island, superiorPlayer) -> String.valueOf(island.getCoopPlayers().stream().filter(SuperiorPlayer::isOnline).count()))
Checking for whether the coop player is online is redundant

2023-04-28 11:28 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/superiorskyblock/service/placeholders/PlaceholdersServiceImpl.java
> +                    .put("island_coop_online", (island, superiorPlayer) -> String.valueOf(island.getCoopPlayers().stream().filter(SuperiorPlayer::isOnline).count()))
Because it conflicts with the COOP pattern, and the term "online" for coop players is redundant, let's maybe rename this to `coops`?

2023-04-28 11:28 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/superiorskyblock/commands/admin/CmdAdminAddCoop.java
> +        if (island.getName().isEmpty())
This check for be similar to the one in `CmdAdminAdd`:
```
        if (superiorPlayer == null) {
            ...
        } else {
            ...
        }
```

2023-11-04 09:24 UTC, closed without merging