Added ability to teleport straight to warp
BG-Software-LLC/SuperiorSkyblock2 pull request #410
Opened 2021-07-31 10:14 UTC by Lukatjee

Also had to modify the SkinsRestorerHook as it didn't want to compile with old code

2021-07-31 10:41 UTC, OmerBenGera requested changes

2021-07-31 10:41 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/superiorskyblock/hooks/SkinsRestorerHook.java
>  import com.bgsoftware.superiorskyblock.api.wrappers.SuperiorPlayer;
Do not edit files that has nothing to do with the feature itself.

2021-07-31 10:41 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/superiorskyblock/commands/CmdWarp.java
> +        if (args.length == 3) {
You assume the third parameter is always the warp's name, however the second parameter is optional.
What will happen if player will run /is warp <warp-name>? The logic you wrote will not occur, and if I am not mistaken, it should. The correct flow should be:
If there are 3 arguments -> third one is the warp's name
If there are two arguments -> check if the second argument is the warp's name.
If it's not the warp's name, then it's probably an island/player's name, and the old logic should occur regularly.
If it is a warp's name, then the player will be teleported to that warp.

Also, not all players can teleport to all warps, and there must be a check for that.
In the original code, the check is done in the requestObjects of MenuWarps.

2021-07-31 10:41 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/superiorskyblock/commands/CmdWarp.java
> +            for (String warpName : island.getIslandWarps().keySet()) {
You should use Island#getWarp instead of looping through all the warps.

2021-07-31 10:41 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/superiorskyblock/menu/MenuWarps.java
> -                superiorPlayer.runIfOnline(Player::closeInventory);
You removed this part and moved it to the simulateClick, however there's no guarantee now that previousMove=false will be called before closing the inventory, which might lead to the previous menu opening for the player.

2021-07-31 10:42 UTC, OmerBenGera commented
Also, please work with the dev branch and not master.

2021-08-01 20:18 UTC, Lukatjee commented
will be switching to dev branch

2021-08-01 20:18 UTC, closed without merging