Added the ability to teleport straight to warp
BG-Software-LLC/SuperiorSkyblock2 pull request #417
Opened 2021-08-01 20:20 UTC by Lukatjee

Attempted the requested changes: https://github.com/BG-Software-LLC/SuperiorSkyblock2/pull/410

2021-08-13 12:21 UTC, OmerBenGera requested changes

2021-08-13 12:21 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/superiorskyblock/commands/CmdWarp.java
> +        System.out.println(args[0]);
This should be removed.

2021-08-13 17:47 UTC, Lukatjee commented on src/main/java/com/bgsoftware/superiorskyblock/commands/CmdWarp.java
> +        System.out.println(args[0]);
Removed that line

2021-08-21 12:26 UTC, JamesSmily commented
Jesus died cause of the fucking scum bag jews that killed him and i'm glad hitler murdered those scum bags like omre and his family. Boy got mad cause i said jesus got killed by the jews which he is also jewish and banned me from the discord and that is why the jews got killed cause of being scum like him. No money poor af living in a poor country relying on minecraft for money but even that didn't work so he quit cause he's depressed.

2021-08-21 12:26 UTC, JamesSmily commented
Jesus died cause of the fucking scum bag jews that killed him and i'm glad hitler murdered those scum bags like omre and his family. Boy got mad cause i said jesus got killed by the jews which he is also jewish and banned me from the discord and that is why the jews got killed cause of being scum like him. No money poor af living in a poor country relying on minecraft for money but even that didn't work so he quit cause he's depressed.

2021-08-28 02:38 UTC, Skizzles commented
@OmerBenGera is this good to merge?

2021-08-28 07:17 UTC, OmerBenGera commented
I still need to do tests, so no

2021-08-28 15:39 UTC, OmerBenGera requested changes
Amazing job, I tested it and it seems to work flawlessly fine.
It's only missing one thing tho - tab completes don't support the warp names yet.
I'd like it to also have tab completes support, so it will show only warp names that you can teleport to.

After that it is added, I will merge the changes.
Good work bud!

2021-08-28 20:19 UTC, OmerBenGera requested changes

2021-08-28 20:19 UTC, OmerBenGera commented on src/main/java/com/bgsoftware/superiorskyblock/commands/CmdWarp.java
> +            case 2 -> CommandTabCompletes.getPlayerIslandsExceptSender(plugin, sender, args[1],
You can't use Java 16 features.

2021-09-04 15:07 UTC, Lukatjee commented
Any updates on this @OmerBenGera ?

2021-09-04 15:14 UTC, merged

2021-09-04 15:15 UTC, OmerBenGera commented
> 
> 
> Any updates on this @OmerBenGera ?

I had to fix some issues with tab completes, but other than that everything was fine and I merged it :)